apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "heos-control.migrationResourceAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: migration
  name: {{ include "heos-control.migrationServiceAccount" . }}
automountServiceAccountToken: false
