// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOperationHistory = `-- name: ListOperationHistory :many
SELECT id, kind, player, state, revision, phase, config_revision, selected_album,
    progress, outcome, error_code, created_at, updated_at, started_at, finished_at
FROM heos.operations
WHERE player = ANY($1::text[])
    AND ($2::boolean OR principal = $3::text)
    AND ($4::text = '' OR player = $4::text)
    AND ($5::text = '' OR state = $5::text)
    AND ($6::text = '' OR kind = $6::text)
    AND ($7::text = '' OR outcome->>'delivery' = $7::text)
    AND ($8::timestamptz IS NULL OR created_at >= $8::timestamptz)
    AND ($9::timestamptz IS NULL OR created_at < $9::timestamptz)
    AND ($10::timestamptz IS NULL OR (created_at, id) < ($10::timestamptz, $11::text))
ORDER BY created_at DESC, id DESC
LIMIT $12::integer
`

type ListOperationHistoryParams struct {
	Players        []string
	IsOperator     bool
	Principal      string
	PlayerFilter   string
	StateFilter    string
	KindFilter     string
	DeliveryFilter string
	CreatedFrom    pgtype.Timestamptz
	CreatedBefore  pgtype.Timestamptz
	BeforeTime     pgtype.Timestamptz
	BeforeID       string
	PageLimit      int32
}

type ListOperationHistoryRow struct {
	ID             string
	Kind           string
	Player         string
	State          string
	Revision       int64
	Phase          string
	ConfigRevision string
	SelectedAlbum  pgtype.Text
	Progress       []byte
	Outcome        []byte
	ErrorCode      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

func (q *Queries) ListOperationHistory(ctx context.Context, arg ListOperationHistoryParams) ([]ListOperationHistoryRow, error) {
	rows, err := q.db.Query(ctx, listOperationHistory,
		arg.Players,
		arg.IsOperator,
		arg.Principal,
		arg.PlayerFilter,
		arg.StateFilter,
		arg.KindFilter,
		arg.DeliveryFilter,
		arg.CreatedFrom,
		arg.CreatedBefore,
		arg.BeforeTime,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOperationHistoryRow
	for rows.Next() {
		var i ListOperationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Player,
			&i.State,
			&i.Revision,
			&i.Phase,
			&i.ConfigRevision,
			&i.SelectedAlbum,
			&i.Progress,
			&i.Outcome,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
