// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package dbgen

import (
	"context"
)

const listMigrations = `-- name: ListMigrations :many
SELECT version, checksum, min_runtime
FROM heos.schema_migrations
ORDER BY version
`

type ListMigrationsRow struct {
	Version    int32
	Checksum   string
	MinRuntime int32
}

func (q *Queries) ListMigrations(ctx context.Context) ([]ListMigrationsRow, error) {
	rows, err := q.db.Query(ctx, listMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMigrationsRow
	for rows.Next() {
		var i ListMigrationsRow
		if err := rows.Scan(&i.Version, &i.Checksum, &i.MinRuntime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
