// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HeosOperation struct {
	ID                 string
	Kind               string
	Player             string
	DeviceKey          string
	Principal          string
	Epoch              string
	State              string
	Revision           int64
	Phase              string
	ConfigRevision     string
	EffectiveArguments []byte
	SelectedAlbum      pgtype.Text
	Progress           []byte
	Outcome            []byte
	ErrorCode          string
	ScheduledFor       pgtype.Timestamptz
	NotAfter           pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
}
