// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeOperation = `-- name: ActiveOperation :one
SELECT o.id, o.kind, o.player, o.device_key, o.principal, o.epoch, o.state, o.revision, o.phase, o.config_revision, o.effective_arguments, o.selected_album, o.progress, o.outcome, o.error_code, o.scheduled_for, o.not_after, o.created_at, o.updated_at, o.started_at, o.finished_at FROM heos.operations o JOIN heos.device_reservations r ON r.operation_id = o.id
WHERE o.player = $1
`

func (q *Queries) ActiveOperation(ctx context.Context, player string) (HeosOperation, error) {
	row := q.db.QueryRow(ctx, activeOperation, player)
	var i HeosOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Player,
		&i.DeviceKey,
		&i.Principal,
		&i.Epoch,
		&i.State,
		&i.Revision,
		&i.Phase,
		&i.ConfigRevision,
		&i.EffectiveArguments,
		&i.SelectedAlbum,
		&i.Progress,
		&i.Outcome,
		&i.ErrorCode,
		&i.ScheduledFor,
		&i.NotAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const countOperations = `-- name: CountOperations :one
SELECT count(*) FROM (SELECT id FROM heos.operations LIMIT $1) bounded
`

func (q *Queries) CountOperations(ctx context.Context, limit int32) (int64, error) {
	row := q.db.QueryRow(ctx, countOperations, limit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const extendRetention = `-- name: ExtendRetention :exec
UPDATE heos.idempotency_records SET expires_at = GREATEST(expires_at, $2)
WHERE operation_id = ANY($1::text[])
`

type ExtendRetentionParams struct {
	Column1   []string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ExtendRetention(ctx context.Context, arg ExtendRetentionParams) error {
	_, err := q.db.Exec(ctx, extendRetention, arg.Column1, arg.ExpiresAt)
	return err
}

const getOperation = `-- name: GetOperation :one
SELECT id, kind, player, device_key, principal, epoch, state, revision, phase, config_revision, effective_arguments, selected_album, progress, outcome, error_code, scheduled_for, not_after, created_at, updated_at, started_at, finished_at FROM heos.operations WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id string) (HeosOperation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i HeosOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Player,
		&i.DeviceKey,
		&i.Principal,
		&i.Epoch,
		&i.State,
		&i.Revision,
		&i.Phase,
		&i.ConfigRevision,
		&i.EffectiveArguments,
		&i.SelectedAlbum,
		&i.Progress,
		&i.Outcome,
		&i.ErrorCode,
		&i.ScheduledFor,
		&i.NotAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertOperation = `-- name: InsertOperation :one
INSERT INTO heos.operations (id, kind, player, device_key, principal, epoch, state,
    config_revision, effective_arguments, created_at, updated_at, scheduled_for, not_after)
VALUES ($1, $2, $3, $4, $5, $6, 'accepted', $7, $8, $9, $9, $10, $11) RETURNING id, kind, player, device_key, principal, epoch, state, revision, phase, config_revision, effective_arguments, selected_album, progress, outcome, error_code, scheduled_for, not_after, created_at, updated_at, started_at, finished_at
`

type InsertOperationParams struct {
	ID                 string
	Kind               string
	Player             string
	DeviceKey          string
	Principal          string
	Epoch              string
	ConfigRevision     string
	EffectiveArguments []byte
	CreatedAt          pgtype.Timestamptz
	ScheduledFor       pgtype.Timestamptz
	NotAfter           pgtype.Timestamptz
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) (HeosOperation, error) {
	row := q.db.QueryRow(ctx, insertOperation,
		arg.ID,
		arg.Kind,
		arg.Player,
		arg.DeviceKey,
		arg.Principal,
		arg.Epoch,
		arg.ConfigRevision,
		arg.EffectiveArguments,
		arg.CreatedAt,
		arg.ScheduledFor,
		arg.NotAfter,
	)
	var i HeosOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Player,
		&i.DeviceKey,
		&i.Principal,
		&i.Epoch,
		&i.State,
		&i.Revision,
		&i.Phase,
		&i.ConfigRevision,
		&i.EffectiveArguments,
		&i.SelectedAlbum,
		&i.Progress,
		&i.Outcome,
		&i.ErrorCode,
		&i.ScheduledFor,
		&i.NotAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertRequest = `-- name: InsertRequest :exec
INSERT INTO heos.idempotency_records (principal, method, endpoint, key, request_hash, operation_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertRequestParams struct {
	Principal   string
	Method      string
	Endpoint    string
	Key         string
	RequestHash []byte
	OperationID string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) error {
	_, err := q.db.Exec(ctx, insertRequest,
		arg.Principal,
		arg.Method,
		arg.Endpoint,
		arg.Key,
		arg.RequestHash,
		arg.OperationID,
		arg.ExpiresAt,
	)
	return err
}

const interruptBatch = `-- name: InterruptBatch :many
UPDATE heos.operations SET state = 'uncertain', phase = 'restart',
    error_code = 'process_interrupted', outcome = jsonb_build_object(
        'device_state', 'unknown', 'playback_may_continue', true,
        'diagnostics', jsonb_build_object('reason', 'process_interrupted', 'rule', NULL,
            'phase', phase, 'detected_at', NULL, 'source', 'recovery', 'changed_fields', '[]'::jsonb)),
    revision = revision + 1, updated_at = $2, finished_at = $2
WHERE id IN (SELECT old.id FROM heos.operations old WHERE old.epoch <> $1 AND old.finished_at IS NULL
    ORDER BY old.id LIMIT $3 FOR UPDATE) RETURNING id
`

type InterruptBatchParams struct {
	Epoch     string
	UpdatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) InterruptBatch(ctx context.Context, arg InterruptBatchParams) ([]string, error) {
	rows, err := q.db.Query(ctx, interruptBatch, arg.Epoch, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJournal = `-- name: LockJournal :one
SELECT epoch, ready FROM heos.journal_control WHERE singleton = true FOR UPDATE
`

type LockJournalRow struct {
	Epoch string
	Ready bool
}

func (q *Queries) LockJournal(ctx context.Context) (LockJournalRow, error) {
	row := q.db.QueryRow(ctx, lockJournal)
	var i LockJournalRow
	err := row.Scan(&i.Epoch, &i.Ready)
	return i, err
}

const lookupRequest = `-- name: LookupRequest :one
SELECT i.operation_id, i.request_hash FROM heos.idempotency_records i
WHERE i.principal = $1 AND i.method = $2 AND i.endpoint = $3 AND i.key = $4
`

type LookupRequestParams struct {
	Principal string
	Method    string
	Endpoint  string
	Key       string
}

type LookupRequestRow struct {
	OperationID string
	RequestHash []byte
}

func (q *Queries) LookupRequest(ctx context.Context, arg LookupRequestParams) (LookupRequestRow, error) {
	row := q.db.QueryRow(ctx, lookupRequest,
		arg.Principal,
		arg.Method,
		arg.Endpoint,
		arg.Key,
	)
	var i LookupRequestRow
	err := row.Scan(&i.OperationID, &i.RequestHash)
	return i, err
}

const pruneOperations = `-- name: PruneOperations :many
DELETE FROM heos.operations WHERE id IN (
    SELECT o.id FROM heos.operations o
    WHERE o.finished_at <= $1 AND NOT EXISTS (
        SELECT 1 FROM heos.idempotency_records i WHERE i.operation_id = o.id AND i.expires_at > $2)
    AND NOT EXISTS (SELECT 1 FROM heos.device_reservations r WHERE r.operation_id = o.id)
    ORDER BY o.finished_at, o.id LIMIT $3 FOR UPDATE OF o
) RETURNING id
`

type PruneOperationsParams struct {
	FinishedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	Limit      int32
}

func (q *Queries) PruneOperations(ctx context.Context, arg PruneOperationsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, pruneOperations, arg.FinishedAt, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readJournal = `-- name: ReadJournal :one
SELECT epoch, ready FROM heos.journal_control WHERE singleton = true FOR SHARE
`

type ReadJournalRow struct {
	Epoch string
	Ready bool
}

func (q *Queries) ReadJournal(ctx context.Context) (ReadJournalRow, error) {
	row := q.db.QueryRow(ctx, readJournal)
	var i ReadJournalRow
	err := row.Scan(&i.Epoch, &i.Ready)
	return i, err
}

const releaseReservations = `-- name: ReleaseReservations :exec
DELETE FROM heos.device_reservations WHERE operation_id = ANY($1::text[])
`

func (q *Queries) ReleaseReservations(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, releaseReservations, dollar_1)
	return err
}

const reserveDevice = `-- name: ReserveDevice :exec
INSERT INTO heos.device_reservations (device_key, operation_id, epoch) VALUES ($1, $2, $3)
`

type ReserveDeviceParams struct {
	DeviceKey   string
	OperationID string
	Epoch       string
}

func (q *Queries) ReserveDevice(ctx context.Context, arg ReserveDeviceParams) error {
	_, err := q.db.Exec(ctx, reserveDevice, arg.DeviceKey, arg.OperationID, arg.Epoch)
	return err
}

const selectAlbum = `-- name: SelectAlbum :one
UPDATE heos.operations SET selected_album = $2, revision = revision + 1, updated_at = $3
WHERE id = $1 AND revision = $4 AND epoch = $5 AND selected_album IS NULL AND finished_at IS NULL RETURNING id, kind, player, device_key, principal, epoch, state, revision, phase, config_revision, effective_arguments, selected_album, progress, outcome, error_code, scheduled_for, not_after, created_at, updated_at, started_at, finished_at
`

type SelectAlbumParams struct {
	ID            string
	SelectedAlbum pgtype.Text
	UpdatedAt     pgtype.Timestamptz
	Revision      int64
	Epoch         string
}

func (q *Queries) SelectAlbum(ctx context.Context, arg SelectAlbumParams) (HeosOperation, error) {
	row := q.db.QueryRow(ctx, selectAlbum,
		arg.ID,
		arg.SelectedAlbum,
		arg.UpdatedAt,
		arg.Revision,
		arg.Epoch,
	)
	var i HeosOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Player,
		&i.DeviceKey,
		&i.Principal,
		&i.Epoch,
		&i.State,
		&i.Revision,
		&i.Phase,
		&i.ConfigRevision,
		&i.EffectiveArguments,
		&i.SelectedAlbum,
		&i.Progress,
		&i.Outcome,
		&i.ErrorCode,
		&i.ScheduledFor,
		&i.NotAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setJournalEpoch = `-- name: SetJournalEpoch :exec
UPDATE heos.journal_control SET epoch = $1, ready = $2 WHERE singleton = true
`

type SetJournalEpochParams struct {
	Epoch string
	Ready bool
}

func (q *Queries) SetJournalEpoch(ctx context.Context, arg SetJournalEpochParams) error {
	_, err := q.db.Exec(ctx, setJournalEpoch, arg.Epoch, arg.Ready)
	return err
}

const transitionOperation = `-- name: TransitionOperation :one
UPDATE heos.operations SET state = $2, revision = revision + 1, phase = $3,
    progress = $4, outcome = $5, error_code = $6, updated_at = $7,
    started_at = CASE WHEN $2 = 'running' THEN COALESCE(started_at, $7) ELSE started_at END,
    finished_at = CASE WHEN $2 IN ('accepted', 'running') THEN NULL ELSE $7 END
WHERE id = $1 AND revision = $8 AND epoch = $9 AND finished_at IS NULL RETURNING id, kind, player, device_key, principal, epoch, state, revision, phase, config_revision, effective_arguments, selected_album, progress, outcome, error_code, scheduled_for, not_after, created_at, updated_at, started_at, finished_at
`

type TransitionOperationParams struct {
	ID        string
	State     string
	Phase     string
	Progress  []byte
	Outcome   []byte
	ErrorCode string
	UpdatedAt pgtype.Timestamptz
	Revision  int64
	Epoch     string
}

func (q *Queries) TransitionOperation(ctx context.Context, arg TransitionOperationParams) (HeosOperation, error) {
	row := q.db.QueryRow(ctx, transitionOperation,
		arg.ID,
		arg.State,
		arg.Phase,
		arg.Progress,
		arg.Outcome,
		arg.ErrorCode,
		arg.UpdatedAt,
		arg.Revision,
		arg.Epoch,
	)
	var i HeosOperation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Player,
		&i.DeviceKey,
		&i.Principal,
		&i.Epoch,
		&i.State,
		&i.Revision,
		&i.Phase,
		&i.ConfigRevision,
		&i.EffectiveArguments,
		&i.SelectedAlbum,
		&i.Progress,
		&i.Outcome,
		&i.ErrorCode,
		&i.ScheduledFor,
		&i.NotAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
